server
{
    server_name fp.areso.pro;
    access_log /var/log/nginx/fp.access.log;
        error_log /var/log/nginx/fp.error.log;
    root /var/www/html/fp;
    index index.html;
    location ~ /\.git
    {
        deny all;
    }
    listen 443 ssl; # managed by Certbot
}
server
{
    if ($host = fp.areso.pro) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    server_name fp.areso.pro;
    listen 80;
    return 404; # managed by Certbot
}
